


LoadConfig:
  model:
      # Load the teacher model into pure mamba
    - path: ${TeacherConfig.dir}
      strict: false
      allow_missing_keys: false # mixer keys are missing
      allow_unexpected_keys: false # all keys from the teacher model are expected
      rename: {
        # order matters
        'module.': '',
        'embeddings.': 'embedding.',
        '.norm.': '.input_layernorm.',
        '.norm_f.': '.final_layernorm.',
        }
      black_list: []
