TrainConfig:
  seed: 42
  activation_checkpointing: true
  mixed_precision: true  
  compile_model: false
  model_dtype: float32
  sharding_strategy: HYBRID_SHARD
  effective_batch_size: 128  # don't divide by n_gpus
  n_tokens: !!float 1e7
  tokenizer: ${TeacherConfig.dir}
