LOAD:
- ./configs/Llama/3B/bases/_supervised.yaml
- ./configs/Llama/3B/hybrid/architecture_0.yaml

DistillConfig:
  name: ${ARCH_NAME}-${SSM_MIXER}-Adapter
BLOCK_NAME: DoubleBlockAdapter
BLOCK_INPUT: {resid_dropout: 0.0, mlp_intermediate_size: 8192, mlp_act_fn: 'silu'}
SSM_MIXER: DiscreteMamba2
SSM_INPUT: {
          use_ref_impl: false,
          d_state: 64, n_qk_heads: 32, n_v_heads: 32, expand: 1, chunk_size: 128, headdim: 128, 
          activation: identity, bias: false, norm_cls: none,
          initializer: {z: default, a_log: default, x: default, B: default, C: default, D: default, out: default, convolution: identity}
          }
ROPE_SCALING: {
  factor: !!float 8,
  low_freq_factor: !!float 1,
  high_freq_factor: !!float 4,
  original_max_position_embeddings: 8192,
  rope_type: llama3,
  }


TeacherConfig:
  dir: meta-llama/Llama-3.1-8B-Instruct
  # dir: meta-llama/Llama-3.1-70B-Instruct
  model_dtype: bfloat16
  mixed_precision: false
TrainDataConfig:
  TorchDataLoader:
    batch_size: 2

LoadConfig:
  model:
    - null # ignore previous LoadConfig.model entries
    - path: <path-to-checkpoint>  # Replace with your checkpoint path
      allow_missing_keys: false # mixer keys are missing
      allow_unexpected_keys: false # all keys from the teacher model are expected
# 
