LOAD: 
# - ./configs/Qwen2/1.5B/bases/load.yaml
- ./configs/Qwen2/1.5B/bases/teacher.yaml
- ./configs/Qwen2/1.5B/bases/optimizer.yaml
- ./configs/Qwen2/1.5B/bases/train.yaml
- ./configs/management.yaml

DistillConfig:
  type: supervised

OptimizerConfig:
  lr: 1.0e-05

TrainConfig:
  n_tokens: !!float 2e10

TrainDataConfig:
  loaders: [RoundRobinLoader, PackingDataLoader, TorchDataLoader]
  RoundRobinLoader:
    train_data_configs:
    - !load_yaml ./configs/data/fineweb_edu.yaml
    - !load_yaml ./configs/data/finemath.yaml
  PackingDataLoader:
    max_seq_len: 2048
  TorchDataLoader:
    num_workers: 0
    batch_size: 8


EvalConfig:

- Evaluation: benchmark
  frequency: 1000
  batch_size: 16
  max_length: 2048
  mixed_precision: true
  eval_at_start: true
  eval_at_end: true
  tokenizer: ${TrainConfig.tokenizer}
  tasks: ["arc_challenge", "arc_easy", "hellaswag", "piqa", "winogrande", "openbookqa", "lambada_openai", "mmlu", "gsm8k", "ifeval", "swde"] #"wikitext"
  enable_tqdm: false
  save_latest: true

- Evaluation: eval_ppl
  frequency: 1000
  mixed_precision: true
  eval_at_start: true
  eval_at_end: true
  save_latest: false
  n_batches: 200
  DataConfig:
    loaders: [RoundRobinLoader, PaddingDataLoader, TorchDataLoader]
    RoundRobinLoader:
      train_data_configs:
        - !load_yaml ./configs/data/pile10k.yaml
    PaddingDataLoader:
      max_seq_len: 2048
    TorchDataLoader:
      num_workers: 0
      batch_size: 8
