LOAD:
- ./configs/Llama/8B/bases/_hstates.yaml
- ./configs/components/llama.yaml

DistillConfig:
  name: llama

TrainConfig:
  activation_checkpointing: true
  DataConfig:
    batch_size: 8
    effective_batch_size: 128

OptimizerConfig:
  optimizer: Adam
  lr: 5.0e-05 # works
  weight_decay: 0.0

LoadConfig:
  model:
      # Load the teacher model into pure mamba
    - path: meta-llama/Llama-3.1-8B-Instruct
      strict: false
      allow_missing_keys: true # mixer keys are missing
      allow_unexpected_keys: false # all keys from the teacher model are expected
      rename: {
        # order matters
        'model.': 'backbone.', 
        'self_attn.': 'mixer.self_attn.', 
        'module.': '',
        'embed_tokens.': 'embedding.',
        '.norm.': '.final_layernorm.',
        }
      black_list: null # don't load these components
      white_list: null # load only these components
