LOAD:
- ./configs/Llama/8B/bases/_matrices.yaml
- ./configs/components/llama.yaml

DistillConfig:
  name: llama

TrainConfig:
  activation_checkpointing: true
  DataConfig:
    batch_size: 1
    effective_batch_size: 64
