LOAD:
- ./configs/Llama/8B/bases/_supervised.yaml
- ./configs/Llama/8B/bases/llama.yaml

DistillConfig:
  name: llama

LoadConfig:
  model:
    # Replace with your checkpoint path or use the template variable below
    - path: <path-to-checkpoint>  # Or: ${ManagementConfig.paths.save_dir}/hstates
      strict: true
