LOAD:
  - ./configs/Phi/1.5B/base/_matrices.yaml
  - ./configs/Phi/1.5B/base/phi.yaml
  
DistillConfig:
  name: test15_phi_from_phi
  teacher_model: microsoft/phi-1_5 # llama, phi
  type: matrices # hstates vs supervised

OptimizerConfig:
  freeze: ["mlp", "embedding", "final_layernorm", "lm_head"] # for DDP optimizer

TrainConfig:
  mixed_precision: false
TrainDataConfig:
  TorchDataLoader:
    batch_size: 2
