LOAD:
  - ./configs/Phi/1.5B/base/_supervised.yaml
  - ./configs/Phi/1.5B/base/phi.yaml

DistillConfig:
  name: test15_phi_from_phi
  teacher_model: microsoft/phi-1_5 # llama, phi
  type: supervised # hstates vs supervised
