LOAD:
  - ./configs/Phi/1.5B/base/optimizer.yaml
  - ./configs/Phi/1.5B/base/train.yaml
  - ./configs/management.yaml
  - ./configs/Phi/1.5B/base/phi.yaml

DistillConfig:
  name: test15_phi_from_phi
  teacher_model: microsoft/phi-1_5 # llama, phi
  type: supervised # hstates vs supervised

TrainConfig:
  n_tokens: !!float 5e9

LoadConfig: {}
