LOAD:
  - ./configs/Phi/1.5B/base/optimizer.yaml
  - ./configs/Phi/1.5B/base/train.yaml
  - ./configs/management.yaml
  - ./configs/Phi/1.5B/base/load.yaml

DistillConfig:
  teacher_model: microsoft/phi-1_5
  type: hstates

TrainConfig:
  n_tokens: !!float 1e10

EvalConfig:

- Evaluation: benchmark
  frequency: 10
  batch_size: 32
  mixed_precision: true
  eval_at_start: true
  eval_at_end: true
  tasks: ["arc_challenge", "arc_easy", "hellaswag", "piqa", "winogrande", "lambada_openai", "mmlu"]
  enable_tqdm: false
  save_latest: false

- Evaluation: eval_hstates
  frequency: 10
  eval_at_start: true
  eval_at_end: true
  save_latest: true
  mixed_precision: true
  n_batches: 200
  DataConfig:
    loaders: [HFDataset, Tokenize, PaddingDataLoader, TorchDataLoader]
    HFDataset:
      path: allenai/c4
      name: en.noclean
      streaming: true
    Tokenize:
      tokenizer: ${TeacherConfig.dir}
      collate_type: text
    PaddingDataLoader:
      max_seq_len: 2048
    TorchDataLoader:
      num_workers: 0
      batch_size: 16
