LOAD:
  - ./configs/Phi/1.5B/base/optimizer.yaml
  - ./configs/Phi/1.5B/base/train.yaml
  - ./configs/management.yaml
  - ./configs/Phi/1.5B/base/load.yaml

DistillConfig:
  teacher_model: microsoft/phi-1_5
  type: supervised


TrainConfig:
  activation_checkpointing: true
  n_tokens: !!float 6e9

EvalConfig:

- Evaluation: eval_hstates
  frequency: !!float inf
  eval_at_start: true
  eval_at_end: false
  save_latest: false
  mixed_precision: true
  n_batches: 200
  DataConfig:
    loaders: [HFDataset, Tokenize, PaddingDataLoader, TorchDataLoader]
    HFDataset:
      path: allenai/c4
      name: en.noclean
      streaming: true
    Tokenize:
      tokenizer: ${TeacherConfig.dir}
      collate_type: text
    PaddingDataLoader:
      max_seq_len: 2048
    TorchDataLoader:
      num_workers: 0
      batch_size: 16

- Evaluation: benchmark
  frequency: 1000
  batch_size: 32
  mixed_precision: true
  eval_at_start: true
  eval_at_end: true
  tasks: ["arc_challenge", "arc_easy", "hellaswag", "piqa", "winogrande", "lambada_openai", "mmlu"]
  enable_tqdm: false
  save_latest: true

- Evaluation: eval_ppl
  frequency: 1000
  mixed_precision: true
  eval_at_start: true
  eval_at_end: true
  save_latest: false
  DataConfig:
    loaders: [JSONIterableDataset, Tokenize, PaddingDataLoader, TorchDataLoader]
    JSONIterableDataset:
      data_dir: <path-to-fineweb-edu-dataset>  # Replace with your FineWeb-Edu dataset path
    Tokenize:
      tokenizer: ${TeacherConfig.dir}
      collate_type: text
    PaddingDataLoader:
      n_tokens: !!float 1e7
      max_seq_len: 2048
    TorchDataLoader:
      num_workers: 0
      batch_size: 8
