TrainConfig:
  seed: 42
  activation_checkpointing: false
  mixed_precision: true  
  model_dtype: bfloat16
  sharding_strategy: HYBRID_SHARD # HYBRID_SHARD, NO_SHARD, or FULL_SHARD
  effective_batch_size: 128  # don't divide by n_gpus
  tokenizer: ${TeacherConfig.dir}

TeacherConfig:
  dir: ${DistillConfig.teacher_model}
  model_dtype: bfloat16
  mixed_precision: true
  activation_checkpointing: false
  compile_model: false
  sharding_strategy: HYBRID_SHARD

TrainDataConfig:
  loaders: [HFDataset, Tokenize, PackingDataLoader, TorchDataLoader]
  HFDataset:
    path: HuggingFaceFW/fineweb-edu
    streaming: true
  Tokenize:
    tokenizer: ${TeacherConfig.dir}
    collate_type: text
  PackingDataLoader:
    max_seq_len: 2048
  TorchDataLoader:
    num_workers: 4
    batch_size: 16
