LOAD:
# Base configs
- ./configs/Qwen2/1.5B/bases/_hstates.yaml
# - ./configs/Qwen2/1.5B/bases/_supervised.yaml
# - ./configs/Qwen2/1.5B/bases/_post_supervised.yaml
# Architecture configs
# - ./configs/Qwen2/1.5B/hybrid/architecture_0.yaml
# - ./configs/Qwen2/1.5B/hybrid/architecture_5.yaml
# - ./configs/Qwen2/1.5B/hybrid/architecture_10.yaml
# - ./configs/Qwen2/1.5B/hybrid/architecture_20.yaml
# - ./configs/Qwen2/1.5B/hybrid/architecture_30.yaml
- ./configs/Qwen2/1.5B/hybrid/architecture_40.yaml

DistillConfig:
  name: ${ARCH_NAME}-${SSM_MIXER}-Adapter
BLOCK_NAME: DoubleBlockAdapter
BLOCK_INPUT: {resid_dropout: 0.0, mlp_intermediate_size: 8960, mlp_act_fn: 'silu'}
ATTN_BIAS: true
SSM_MIXER: DiscreteMamba2
SSM_INPUT: {
  use_ref_impl: false,
  d_state: 128,  headdim: 128,
  n_qk_heads: 12, n_v_heads: 12, 
  expand: 1, chunk_size: 128, activation: identity, use_ref_impl: false, bias: false, norm_cls: none,
  initializer: {a_log: default, x: default, B: default, C: default, D: default, z: default, out: default, convolution: identity}
  }


LoadConfig:
  model:
    - null # ignore previous LoadConfig.model entries
    - path: <path-to-checkpoint>  # Replace with your checkpoint path
      allow_missing_keys: false # mixer keys are missing
      allow_unexpected_keys: false # all keys from the teacher model are expected
