LOAD:
- ./configs/Qwen2/1.5B/bases/_hstates.yaml
- ./configs/Qwen2/1.5B/qwen/components.yaml

DistillConfig:
  name: Qwen2
  hstates_gap: 1 # 2

OptimizerConfig:
  lr: 1.0e-04

LoadConfig:
  model:
    - null # ignore previous LoadConfig.model entries
    - path: ${TeacherConfig.dir}
      allow_missing_keys: false # <- use this for distillation scenarios
      # allow_missing_keys: true # mixer keys are missing
      allow_unexpected_keys: false # all keys from the teacher model are expected
      rename: {
        # order matters
        'model.': 'backbone.', 
        'self_attn.': 'mixer.self_attn.', 
        'module.': '',
        'embed_tokens.': 'embedding.',
        '.norm.': '.final_layernorm.',
        }
      black_list: [
        lm_head,   # <- lm_head is tied to the embedding layer, no need to load it
        # self_attn, # <- use this for distillation scenarios
      ]
