TrainDataConfig:
  loaders: [JSONIterableDataset, Tokenize, PaddingDataLoader, TorchDataLoader]
  JSONIterableDataset:
    data_dir: configs/smoke/data_shuffle_a
  Tokenize:
    tokenizer: sshleifer/tiny-gpt2
    collate_type: text
    local_files_only: true
  PaddingDataLoader:
    max_seq_len: 8
  TorchDataLoader:
    batch_size: 1
    num_workers: 0
