LOAD:
  - configs/smoke/tiny_cuda_ddp_fineweb_edu_production_loader_supervised.yaml

ManagementConfig:
  paths:
    base_dir: /home/abick/storage/mohawk/fineweb_edu_direct_shard_cuda_ddp
    save_dir: /home/abick/storage/mohawk/fineweb_edu_direct_shard_cuda_ddp/save
    tmp_dir: /home/abick/storage/mohawk/fineweb_edu_direct_shard_cuda_ddp/tmp
  env_vars:
    WANDB_DIR: /home/abick/storage/mohawk/fineweb_edu_direct_shard_cuda_ddp/wandb
    TORCH_HOME: /home/abick/storage/mohawk/fineweb_edu_direct_shard_cuda_ddp/torch_home

DistillConfig:
  name: Tiny-CUDA-DDP-FineWeb-Edu-Direct-Shard-Supervised-Smoke

TrainDataConfig:
  HFDataset:
    path: parquet
    name: null
    data_files:
      train:
        - https://huggingface.co/datasets/HuggingFaceFW/fineweb-edu/resolve/main/sample/100BT/000_00000.parquet
