LOAD:
  - configs/smoke/tiny_cpu_mixed_precision.yaml

ManagementConfig:
  paths:
    base_dir: /tmp/mohawk_tiny_mixed_precision_resume_cpu_run
    save_dir: /tmp/mohawk_tiny_mixed_precision_resume_cpu_run/save
    tmp_dir: /tmp/mohawk_tiny_mixed_precision_resume_cpu_run/tmp
  env_vars:
    TORCH_HOME: /tmp/mohawk_tiny_mixed_precision_resume_cpu_run/torch_home
    HF_DATASETS_CACHE: /tmp/mohawk_tiny_mixed_precision_resume_cpu_run/huggingface/datasets
    HF_HUB_CACHE: /tmp/mohawk_tiny_mixed_precision_resume_cpu_run/huggingface/hub

DistillConfig:
  name: Tiny-CPU-Mixed-Precision-Resume-Smoke

TrainConfig:
  n_tokens: 32

LoadConfig:
  model:
    - path: /tmp/mohawk_tiny_mixed_precision_cpu_run/save
  optimizer:
    path: /tmp/mohawk_tiny_mixed_precision_cpu_run/save
  scheduler:
    path: /tmp/mohawk_tiny_mixed_precision_cpu_run/save
