LOAD:
  - configs/smoke/tiny_cpu_mixed_precision.yaml

ManagementConfig:
  paths:
    base_dir: /tmp/mohawk_tiny_mixed_precision_lazy_cpu_run
    save_dir: /tmp/mohawk_tiny_mixed_precision_lazy_cpu_run/save
    tmp_dir: /tmp/mohawk_tiny_mixed_precision_lazy_cpu_run/tmp
  env_vars:
    TORCH_HOME: /tmp/mohawk_tiny_mixed_precision_lazy_cpu_run/torch_home
    HF_DATASETS_CACHE: /tmp/mohawk_tiny_mixed_precision_lazy_cpu_run/huggingface/datasets
    HF_HUB_CACHE: /tmp/mohawk_tiny_mixed_precision_lazy_cpu_run/huggingface/hub

DistillConfig:
  name: Tiny-CPU-Mixed-Precision-Lazy-Load-Smoke

TrainConfig:
  init_fn: lazy
  n_tokens: 16

LoadConfig:
  model:
    - path: /tmp/mohawk_tiny_mixed_precision_cpu_run/save
      allow_missing_keys: false
      allow_unexpected_keys: false
