LOAD:
  - configs/smoke/tiny_cuda_ddp_fineweb_edu_production_loader_supervised.yaml

ManagementConfig:
  paths:
    base_dir: /home/abick/storage/mohawk/fineweb_edu_production_loader_cuda_fsdp
    save_dir: /home/abick/storage/mohawk/fineweb_edu_production_loader_cuda_fsdp/save
    tmp_dir: /home/abick/storage/mohawk/fineweb_edu_production_loader_cuda_fsdp/tmp
  env_vars:
    WANDB_DIR: /home/abick/storage/mohawk/fineweb_edu_production_loader_cuda_fsdp/wandb
    TORCH_HOME: /home/abick/storage/mohawk/fineweb_edu_production_loader_cuda_fsdp/torch_home

DistillConfig:
  name: Tiny-CUDA-FSDP-FineWeb-Edu-Production-Loader-Supervised-Smoke

TrainConfig:
  wrapper_type: fsdp
  sharding_strategy: FULL_SHARD

TeacherConfig:
  wrapper_type: fsdp
  sharding_strategy: FULL_SHARD
