LOAD:
  - configs/smoke/tiny_cuda_ddp_bfloat16_gradient_accumulation.yaml

ManagementConfig:
  paths:
    base_dir: /home/abick/mohawk/artifacts/gpu_smoke/tiny_cuda_ddp_multinode_bfloat16_gradient_accumulation
    save_dir: /home/abick/mohawk/artifacts/gpu_smoke/tiny_cuda_ddp_multinode_bfloat16_gradient_accumulation/save
    tmp_dir: /home/abick/mohawk/artifacts/gpu_smoke/tiny_cuda_ddp_multinode_bfloat16_gradient_accumulation/tmp
  env_vars:
    TORCH_HOME: /home/abick/mohawk/artifacts/gpu_smoke/tiny_cuda_ddp_multinode_bfloat16_gradient_accumulation/torch_home
    HF_DATASETS_CACHE: /home/abick/mohawk/artifacts/gpu_smoke/tiny_cuda_ddp_multinode_bfloat16_gradient_accumulation/huggingface/datasets

DistillConfig:
  name: Tiny-CUDA-DDP-Multinode-BFloat16-Gradient-Accumulation-Smoke

TrainConfig:
  effective_batch_size: 8
  n_tokens: 64

TrainDataConfig:
  JSONIterableDataset:
    data_dir: configs/smoke/data_ddp_multinode
