TeacherConfig:

  # dir: meta-llama/Llama-3.1-70B-Instruct
  # model_dtype: bfloat16
  # mixed_precision: false

  dir: meta-llama/Llama-3.1-8B-Instruct
  model_dtype: float32
  mixed_precision: true

  activation_checkpointing: false
  compile_model: false
  sharding_strategy: HYBRID_SHARD
